# when using the default proxy server port
local_backend: true

backend:
  name: git-gateway

# Sample collection, using for config setup
collections:
  - name: "category"
    label: "Product Category"
    

  - name: "products"
    label: "Products"
    folder: "src/content/products"
    create: true
    identifier_field: name
    slug: "{{fields.name}}" # Ensure only the 'name' field is used for the filename
    extension: json
    fields:
      - { label: "Name", name: "name", widget: "string" }
      - { label: "Price", name: "price", widget: "number" }
      - { label: "Stock", name: "stock", widget: "number" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Featured Image", name: "image", widget: "image" }

media_folder: "src/assets/images" # Media files will be stored in the repo under static/images/uploads
public_folder: "src/assets/images" # The src attribute for uploaded media will begin with /images/uploads
